name: psalmody
description: A Flutter application for learning and praying Psalms.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
#  connectivity: ^0.4.5+6
  path_provider: ^1.6.5
  sqflite: ^1.3.0
  just_audio: ^0.1.5
  flutter_slidable: ^0.5.4
  share: '>=0.6.4+2 <2.0.0'
  open_file: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - mezmurs.json
     - assets/images/Meskerem/
     - assets/images/abiy_tsom/
     - assets/images/Hidar/
     - assets/images/Kiremt/
     - assets/images/Tahisas/
     - assets/images/Tikimt/
     - assets/images/Tinsae/
     - assets/images/Tir/
     - assets/images/Yekatit/
     - assets/images/Tikimt/5.jpg
     - assets/images/abiy_tsom/9.jpg
     - assets/images/abiy_tsom/2.jpg
     - assets/images/Tinsae/14.jpg
     - assets/images/Kiremt/17.jpg
     - assets/images/Kiremt/13.jpg
     - assets/PDFs/
     - assets/PDFs/መጋቢት_ግንቦት_ግጻዌ.pdf
     - assets/PDFs/የመዝሙራት_ግጻዌ.pdf
     - assets/PDFs/መስከረም_ህዳር_ግጻዌ.pdf
     - assets/PDFs/ታህሳስ_የካቲት_ግጻዌ.pdf
     - assets/PDFs/ሰኔ_ጷግሜን_ግጻዌ.pdf
     - assets/PDFs/የተውሳክ_ግጻዌ.pdf





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
